In [1]:
import os
import sys
import pandas as pd
import numpy as np
import re

In [2]:
scripts_path = os.path.abspath(os.path.join('../scripts'))
if scripts_path not in sys.path:
    sys.path.insert(0,scripts_path)

In [3]:
TRAIN_SET = '../data/first-train.slist'
TRUE_VALUES_SET = '../data/2018.csv'
SPS_INDEX = 2
START_TIME_INDEX = 3
TIME_WINDOW = 10
WAIT_TIME_WINDOW = 1

In [4]:
header = pd.read_csv(TRAIN_SET, sep='\t', nrows=0).columns[0].split(', ')

# Number of samples per second
sps = int(re.findall(r'\d+', header[SPS_INDEX])[0])
# Starting time
startTime = pd.to_datetime(header[START_TIME_INDEX])

In [5]:
X = pd.read_csv(TRAIN_SET, sep='\t', header=0, names=["1", "2", "3", "4", "5", "6"])
X = X.to_numpy().reshape(-1)
X = X[~(np.isnan(X))]
X = X.reshape(X.shape[0], 1)
X

array([[-6731.],
       [-6694.],
       [-6757.],
       ...,
       [-3503.],
       [-3296.],
       [-3129.]])

In [6]:
# Compute ending time
number_of_seconds = (X.shape[0] - 1) / sps # First sample is at starting time -> subtract 1
endTime = startTime + pd.to_timedelta(number_of_seconds, unit='s')

In [88]:
catalog = pd.read_csv(TRUE_VALUES_SET)
catalog["origintime"] = pd.to_datetime(catalog["origintime"])
catalog = catalog[(catalog["origintime"] >= startTime) & (catalog["origintime"] <= endTime)]
catalog.sort_values("origintime")
catalog

event_id          origintime  magnitude magnitude_source max_mmi  \
730         0 2018-04-09 00:59:58        1.8              OGS       0   
731         0 2018-04-09 09:01:57        2.1              OGS       0   
732         0 2018-04-09 09:26:31        3.4              OGS       0   
733         0 2018-04-09 09:50:09        2.2              OGS       0   
734         0 2018-04-09 10:22:20        4.0              OGS       6   
735         0 2018-04-09 11:05:28        1.9              OGS       0   
736         0 2018-04-09 12:33:19        1.9              OGS       0   
737         0 2018-04-09 12:33:19        1.9              OGS       0   
738         0 2018-04-09 14:04:43        2.9              OGS       0   
739         0 2018-04-09 18:37:00        2.4              OGS       0   
740         0 2018-04-09 19:14:01        2.2              OGS       0   
741         0 2018-04-09 19:51:26        2.0              OGS       0   
742         0 2018-04-09 20:30:20        2.2              OGS       0   
743         0 2018-04-09 21:26:41        2.8              OGS       0   
744         0 2018-04-10 16:57:49        2.3              OGS       0   
745         0 2018-04-10 21:20:43        2.1              OGS       0   
746         0 2018-04-10 21:39:21        1.7              OGS       0   
747         0 2018-04-10 22:19:06        2.6              OGS       0   
748         0 2018-04-11 03:32:07        2.0              OGS       0   
749         0 2018-04-11 11:26:31        2.0              OGS       0   
750         0 2018-04-11 11:36:01        1.9              OGS       0   
751         0 2018-04-11 13:54:14        2.4              OGS       0   
752         0 2018-04-11 18:02:23        1.9              OGS       0   
753         0 2018-04-11 23:08:17        2.3              OGS       0   
754         0 2018-04-11 23:37:03        2.3              OGS       0   
755         0 2018-04-12 01:33:22        2.7              OGS       0   
756         0 2018-04-12 04:42:27        2.3              OGS       0   
757         0 2018-04-12 06:49:04        2.1              OGS       0   
758         0 2018-04-12 13:53:16        2.1              OGS       0   
759         0 2018-04-12 20:12:14        2.3              OGS       0   
760         0 2018-04-12 23:56:07        2.9              OGS       2   

     latitude  longitude  depth_km  err_lat  err_lon  err_depth  \
730  36.45094  -98.79978     5.645      0.6      0.5        0.8   
731  36.21448  -97.57076     4.829      0.3      0.3        0.9   
732  36.21511  -97.56857     5.189      0.2      0.3        0.8   
733  36.29543  -97.53089     5.152      0.4      0.4        1.2   
734  36.21847  -97.57350     4.274      0.2      0.3        0.8   
735  36.21376  -97.55272     6.744      0.3      0.3        1.0   
736  35.38129  -98.09020     5.000      0.7      0.7        1.8   
737  35.37896  -98.08983     3.575      0.9      0.7        2.1   
738  36.21164  -97.55554     3.587      0.2      0.3        0.8   
739  36.32548  -97.53697     4.454      0.3      0.3        0.9   
740  36.42793  -96.92060     5.510      0.3      0.4        0.5   
741  36.33742  -97.59342     6.483      0.3      0.4        1.2   
742  36.21499  -97.55621     3.452      0.3      0.3        1.0   
743  36.72215  -99.37740     3.138      0.6      0.7        0.9   
744  36.73790  -97.72086     7.987      0.3      0.3        1.2   
745  36.21651  -97.56748     5.808      0.4      0.4        1.2   
746  35.43995  -97.84804     5.000      1.3      1.6        1.7   
747  36.22791  -97.33907     6.747      0.2      0.3        1.1   
748  36.11065  -97.74716     6.066      0.3      0.4        0.7   
749  36.36737  -98.15361     7.140      0.5      0.5        1.9   
750  36.10652  -97.74876     5.546      0.4      0.4        0.8   
751  36.27956  -97.50670     3.127      0.3      0.3        1.0   
752  35.93220  -95.14093     4.222      1.1      0.8        3.0   
753  35.55437  -96.75212     4.776      0.5      0.7        

In [111]:
y = np.zeros((X.shape[0], 1))
y.shape

(34560001, 1)

In [110]:
for date in catalog["origintime"]:
    seconds_to_hq = (date - startTime).seconds
    index_in_data = seconds_to_hq * sps
    y[int(index_in_data / X.shape[0])] = 1

3598
32517
33991
35409
37340
39928
45199
45199
50683
67020
69241
71486
73820
77201
61069
76843
77961
80346
12727
41191
41761
50054
64943
83297
85023
5602
16947
24544
49996
72734
86167


In [8]:
X

array([[-6731.],
       [-6694.],
       [-6757.],
       ...,
       [-3503.],
       [-3296.],
       [-3129.]])

In [22]:
time_hq = pd.to_datetime("2018-04-09 10:22:18")
second_to_hq = (time_hq - startTime).seconds

In [37]:
time_window = X[0:6000]

In [38]:
time_window.shape

(6000, 1)

In [39]:
time_window = time_window - np.mean(time_window)

In [68]:
change_of_sign = time_window[1:] * time_window[:-1]
#change_of_sign[change_of_sign < -100].shape[0]
(change_of_sign < -100000).sum()

5

In [75]:
time_window_hq = X[second_to_hq * sps: second_to_hq * sps + 6000]
time_window_hq = time_window_hq - np.mean(time_window_hq)
change_of_sign = time_window_hq[1:] * time_window_hq[:-1]
#change_of_sign[change_of_sign < -100].shape[0]
(change_of_sign < -100000).sum()

551

In [84]:
def count_signs_per_row(X, amplitude):
    first_kernel = X[:,1:]
    print(first_kernel.shape)
    second_kernel = X[:,:-1]
    print(second_kernel.shape)
    change_of_sign = first_kernel * second_kernel
    return np.sum(change_of_sign < -amplitude, axis=1)

In [86]:
count_signs_per_row(time_window_hq.reshape(1, time_window_hq.shape[0]), 100000)

(1, 5999)
(1, 5999)


array([551])

In [87]:
count_signs_per_row(time_window.reshape(1, time_window.shape[0]), 100000)

(1, 5999)
(1, 5999)


array([5])

In [47]:
def aggregate_window(X):
    N = X.shape[0]
    window_size = TIME_WINDOW*sps
    drop_size = WAIT_TIME_WINDOW*sps
    total_window_size = window_size + drop_size    
    number_window = np.math.floor(N / total_window_size)
    X = X[:number_window*total_window_size]
    X_dropped = np.array(np.split(X.reshape(-1), number_window))[:, :window_size]
    
    return np.mean(X_dropped, axis=1)